### PR TITLE
Fix tokenize with capture groups

### LINKED ISSUE #635: Problem with `tokenize` or regexs
I ran into this issue when the [`functx:lines` function](http://www.xqueryfunctions.com/xq/functx_lines.html) didn't seem to work for me, giving me an extra blank line after each line.

But I can find a simple reproducer using an example from: https://www.altova.com/xpath-xquery-reference/fn-tokenize which says:

>  For example:
> `fn:tokenize("abracadabra", "(ab)|(a)")` returns `("", "r", "c", "d", "r", "")`

But with fontoxpath:

```js
var fontoxpath = require("fontoxpath")

console.log(fontoxpath.evaluateXPathToStrings(
'fn:tokenize("abracadabra", "(ab)|(a)")',
 null, 
undefined, 
undefined,
 {language: fontoxpath.evaluateXPath.XQUERY_3_1_LANGUAGE}))
```

Output:

```js
[
  '',          'ab',
  'undefined', 'r',
  'undefined', 'a',
  'c',         'undefined',
  'a',         'd',
  'ab',        'undefined',
  'r',         'undefined',
  'a',         ''
]
```

Looks like the captures are being incorrectly returned as part of the results of `tokenize`.

### PR DESCRIPTION
**Pull request by DrRataplan**
Fixes a few tests as well!

Also fixes #635. Thanks @rrthomas for finding it!

### CODE REVIEW

**Comment by DrRataplan** [comment]
@devatwork could you help me out here? It seems like my push access to the repo is revoked. Didn't we end up at me retaining `maintainer` rights?

**Comment by devatwork** [comment]
@Erikvl87 Can you advice?

**Comment by Erikvl87** [comment]
@DrRataplan Could you try to add at least a single reviewer and get approval before merging?

**Comment by DrRataplan** [comment]
I am unable to add reviewers. @bwrrp could you review this somewhere this week? No hurry.

**Comment by Erikvl87** [comment]
@DrRataplan, the individual `Maintainer` permission granted to you was inadvertently revoked during your removal from the FontoXML organization. You have been re-added as a `Maintainer`, which should resolve the issue of not being able to add the required reviewers.

**Comment by DrRataplan** [comment]
It works. Thanks!

**Review by bwrrp — APPROVED** [review]
Nice! TIL about [RegExp.prototype[@@split]](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/@@split) and its behavior around capture groups.

**Pull request merged**
